name: order_food
description: "Food/Restaurant Shopping App with Firebase & GetX"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  firebase_messaging: ^16.1.1

  # Notifications
  flutter_local_notifications: ^20.1.0

  # Image / Media
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2

  # UI Enhancement
  google_fonts: ^8.0.2
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  connectivity_plus: ^7.0.0
  logger: ^2.6.2
  flutter_chat_ui: ^2.11.1
  flutter_chat_types: ^3.6.2
  flutter_speed_dial: ^7.0.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.3.1
  flutter_screenutil: ^5.9.3
  google_maps_flutter: ^2.13.1
  photo_view: ^0.15.0
  loading_animation_widget: ^1.3.0
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
